name: PHP CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use PHP
    - name: composer install, phpunit
      run: |
        composer install
        vendor/bin/phpunit
